name: test
on: [push, pull_request]

jobs:
  test-rootless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Disable AppArmor userns restriction
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - name: Test (rootless)
        run: cargo test --release

  test-privileged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test (privileged)
        run: sudo -E env "PATH=$PATH" cargo test --release
        env:
          RONLY_TEST_MODE: privileged
